# Generated by Django 3.1.6 on 2021-02-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_auto_20210221_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='resource',
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='paths.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='paths.area'),
        ),
    ]
