# Generated by Django 3.1.8 on 2021-04-19 01:08

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ForeignKey(default=posts.models.Post.type_default, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='posts.posttype'),
        ),
    ]
