# Generated by Django 3.1.6 on 2021-02-21 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210221_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='posts.posttype'),
        ),
    ]
